# Generated by Django 2.1.2 on 2018-10-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='slug',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
