# Generated by Django 2.1.2 on 2018-10-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_repo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='sync_issues',
            field=models.BooleanField(default=False),
        ),
    ]
