# Generated by Django 2.1.2 on 2018-10-25 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_repo_sync_issues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repo',
        ),
    ]
