# Generated by Django 2.1.2 on 2018-10-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0006_delete_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('content_raw', models.TextField()),
                ('content_html', models.TextField()),
                ('priority', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
