# Generated by Django 2.1.2 on 2018-10-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_issues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issues',
            new_name='Issue',
        ),
    ]
