# Generated by Django 2.1.2 on 2018-10-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20181026_1437'),
        ('issues', '0008_auto_20181026_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='repo.Repo'),
        ),
    ]
