# Generated by Django 2.1.2 on 2018-10-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20181026_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
