# Generated by Django 2.1.2 on 2018-10-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_issue_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('content_raw', models.TextField()),
                ('content_html', models.TextField()),
                ('assignee', models.CharField(max_length=255)),
                ('created_at_bb', models.DateTimeField()),
                ('updated_at_bb', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
