# Generated by Django 2.1.2 on 2018-10-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_auto_20181029_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='issues.Issue'),
        ),
    ]
