# Generated by Django 2.1.2 on 2018-10-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_comment_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_raw',
            field=models.TextField(null=True),
        ),
    ]
