#!/usr/bin/env python
from django.utils.crypto import get_random_string
import re


filename = 'main/local_settings.py'

chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'
key = get_random_string(50, chars)

with open(filename, 'r') as file :
  filedata = file.read()

re_secret_key = re.compile('^SECRET_KEY = .+$', re.M)
filedata = re_secret_key.sub("SECRET_KEY = '%s'" % key, filedata)

# Write the file out again
with open(filename, 'w') as file:
    file.write(filedata)
