# Generated by Django 2.1.2 on 2018-10-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_fetchqueue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fetchqueue',
            old_name='repository_name',
            new_name='repository_slug',
        ),
    ]
