# Generated by Django 2.1.2 on 2018-10-26 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_auto_20181026_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetchqueue',
            name='repository_slug',
        ),
        migrations.AddField(
            model_name='fetchqueue',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='repo.Repo'),
        ),
        migrations.AddField(
            model_name='repo',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
