# Generated by Django 2.1.2 on 2018-10-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20181028_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='num_issues',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
